# Generated by Django 5.1.1 on 2024-09-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.CharField(max_length=255),
        ),
    ]
