# Generated by Django 5.1.1 on 2024-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_tag_name_alter_task_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                null=True, related_name="tasks", to="task.tag"
            ),
        ),
    ]
