# Generated by Django 5.1.1 on 2024-09-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_alter_task_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("is_completed", "-created_at")},
        ),
    ]
