# Generated by Django 5.1.1 on 2024-09-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
