# Generated by Django 5.1.1 on 2024-09-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0006_alter_task_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
